name: Dev
variables:
  - name: BaseURL
    value: http://dooeed.test/api
  - name: token
    value: 20|IE3NFISzlBGgE7BU9haqTVH39G6WOkPSsAr9XXGb82afff7e
  - name: user_id
    value:
      type: number
      data: 01a0bd09-89d0-70d1-8f0a-9bfd663fd4c4
  - name: user_name
    value: Oim Trust
  - name: user_email
    value: oim@gmail.com
